### PR TITLE
Fixes mic not working in google assistant.

### PR DESCRIPTION
**Pull request by nazandrake**
Fixes "Ok Google" hotword detection and mic not working in google assistant.

### CODE REVIEW

**Comment by mountaser** [comment]
Tested??

**Comment by nazandrake** [comment]
Yes, tested on my own device.

**Comment by nazandrake** [comment]
Ok, actually this will provoke part disabling of noise cancelation and during call can trigger voice returning to the remote site(on really loud speakers).

**Comment by ghpranav** [comment]
I don't get the point. Why do we need a fix for something which is already working?

**Comment by nazandrake** [comment]
On my Mi A1 it doesn't work without those changes. All google voice related functions will not work unless disable the noise cancelation...

**Comment by nazandrake** [comment]
Ok, I missed the point that we don't need to actually disable the noise cancelation... but rather to have it only disabled for voice rec. 
I've been testing this setup for several days now and it seems that there are no regressions in it.

**Comment by armujahid** [comment]
@ghpranav I can confirm that `Ok Google` is not working (without headset) on latest treble RR-O-v6.1-20180708 with open_gapps-arm64-8.1-nano-20180805. It works fine only if headset is plugged in.

**Pull request closed without merging**
